CREATE DATABASE paineladm;

USE paineladm;

DROP TABLE IF EXISTS locais;

CREATE TABLE locais (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nome VARCHAR(100) NOT NULL,
  descricao TEXT NOT NULL,
  tipo VARCHAR(50) NOT NULL,
  cidade VARCHAR(100) NOT NULL,
  endereco VARCHAR(150) NOT NULL,
  imagem VARCHAR(255) NOT NULL,
  criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
